/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.fdj32;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@ComponentScan
@EnableAutoConfiguration
@SpringBootApplication
public class App {

    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);
    }
}
