package https.api_ewaypayments_com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.9
 * 2024-08-06T16:29:11.450+08:00
 * Generated source version: 3.5.9
 *
 */
@WebService(targetNamespace = "https://api.ewaypayments.com/", name = "Rapid3.0Soap")
@XmlSeeAlso({https.api_ewaypayments.ObjectFactory.class})
public interface Rapid30Soap {

    /**
     * PCI compliant customers can call DirectCustomerCreate to create token customers and save credit card data.
     */
    @WebMethod(operationName = "DirectCustomerUpdate", action = "https://api.ewaypayments.com/DirectCustomerUpdate")
    @RequestWrapper(localName = "DirectCustomerUpdate", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectCustomerUpdate")
    @ResponseWrapper(localName = "DirectCustomerUpdateResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectCustomerUpdateResponse")
    @WebResult(name = "DirectCustomerUpdateResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.DirectCustomerResponse directCustomerUpdate(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.DirectCustomerRequest request
    );

    /**
     * Cancels a previous transaction where the Method was AUTHORISE
     */
    @WebMethod(operationName = "CancelAuthorisation", action = "https://api.ewaypayments.com/CancelAuthorisation")
    @RequestWrapper(localName = "CancelAuthorisation", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CancelAuthorisation")
    @ResponseWrapper(localName = "CancelAuthorisationResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CancelAuthorisationResponse")
    @WebResult(name = "CancelAuthorisationResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.CancelAuthorisationResponse2 cancelAuthorisation(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.CancelAuthorisationRequest request
    );

    /**
     * Returns an access code and echoes the customer data received in the request. The access code is used for all further requests associated with this transaction.
     */
    @WebMethod(operationName = "CreateAccessCode", action = "https://api.ewaypayments.com/CreateAccessCode")
    @RequestWrapper(localName = "CreateAccessCode", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CreateAccessCode")
    @ResponseWrapper(localName = "CreateAccessCodeResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CreateAccessCodeResponse")
    @WebResult(name = "CreateAccessCodeResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.CreateAccessCodeResponse2 createAccessCode(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.CreateAccessCodeRequest request
    );

    /**
     * Returns an access code and a return Url which inidicates to a highly secure page hosted at eWaypayments site.
     */
    @WebMethod(operationName = "CreateAccessCodeShared", action = "https://api.ewaypayments.com/CreateAccessCodeShared")
    @RequestWrapper(localName = "CreateAccessCodeShared", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CreateAccessCodeShared")
    @ResponseWrapper(localName = "CreateAccessCodeSharedResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CreateAccessCodeSharedResponse")
    @WebResult(name = "CreateAccessCodeSharedResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.CreateAccessCodeSharedResponse2 createAccessCodeShared(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.CreateAccessCodeSharedRequest request
    );

    /**
     * PCI compliant customers can call DirectPayment to create payments with or without CVN information
     */
    @WebMethod(operationName = "DirectPayment", action = "https://api.ewaypayments.com/DirectPayment")
    @RequestWrapper(localName = "DirectPayment", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectPayment")
    @ResponseWrapper(localName = "DirectPaymentResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectPaymentResponse")
    @WebResult(name = "DirectPaymentResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.DirectPaymentResponse2 directPayment(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.DirectPaymentRequest request
    );

    /**
     * PCI compliant customers can call DirectCustomerCreate to create token customers and save credit card data.
     */
    @WebMethod(operationName = "DirectCustomerCreate", action = "https://api.ewaypayments.com/DirectCustomerCreate")
    @RequestWrapper(localName = "DirectCustomerCreate", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectCustomerCreate")
    @ResponseWrapper(localName = "DirectCustomerCreateResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectCustomerCreateResponse")
    @WebResult(name = "DirectCustomerCreateResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.DirectCustomerResponse directCustomerCreate(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.DirectCustomerRequest request
    );

    /**
     * Returns a list of customers that match the filter in the request.
     */
    @WebMethod(operationName = "DirectCustomerSearch", action = "https://api.ewaypayments.com/DirectCustomerSearch")
    @RequestWrapper(localName = "DirectCustomerSearch", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectCustomerSearch")
    @ResponseWrapper(localName = "DirectCustomerSearchResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectCustomerSearchResponse")
    @WebResult(name = "DirectCustomerSearchResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.DirectCustomerSearchResponse2 directCustomerSearch(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.DirectCustomerSearchRequest request
    );

    /**
     * Returns a list of settlement summaries or settlement transactions that match the filter in the request.
     */
    @WebMethod(operationName = "SettlementSearch", action = "https://api.ewaypayments.com/SettlementSearch")
    @RequestWrapper(localName = "SettlementSearch", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.SettlementSearch")
    @ResponseWrapper(localName = "SettlementSearchResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.SettlementSearchResponse")
    @WebResult(name = "SettlementSearchResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.SettlementReportResponse settlementSearch(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.SettlementReportRequest request
    );

    /**
     * Master Users can Upsert API Credentials for specific users.
     */
    @WebMethod(operationName = "APICredentials", action = "https://api.ewaypayments.com/APICredentials")
    @RequestWrapper(localName = "APICredentials", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.APICredentials")
    @ResponseWrapper(localName = "APICredentialsResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.APICredentialsResponse")
    @WebResult(name = "APICredentialsResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.APICredentialsResponse2 apiCredentials(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.APICredentialsRequest request
    );

    /**
     * PCI compliant customers can call DirectAuthorisation to create authorisations with or without CVN information
     */
    @WebMethod(operationName = "DirectAuthorisation", action = "https://api.ewaypayments.com/DirectAuthorisation")
    @RequestWrapper(localName = "DirectAuthorisation", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectAuthorisation")
    @ResponseWrapper(localName = "DirectAuthorisationResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectAuthorisationResponse")
    @WebResult(name = "DirectAuthorisationResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.DirectAuthorisationResponse2 directAuthorisation(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.DirectAuthorisationRequest request
    );

    /**
     * Returns a list of user message that match the given API codes
     */
    @WebMethod(operationName = "APICodeLookup", action = "https://api.ewaypayments.com/APICodeLookup")
    @RequestWrapper(localName = "APICodeLookup", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.APICodeLookup")
    @ResponseWrapper(localName = "APICodeLookupResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.APICodeLookupResponse")
    @WebResult(name = "APICodeLookupResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.CodeLookupResponse apiCodeLookup(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.CodeLookupRequest request
    );

    /**
     * Using a previously created access code, a merchant can request all the relevant details of a transaction from eWAY.
     */
    @WebMethod(operationName = "GetAccessCodeResult", action = "https://api.ewaypayments.com/GetAccessCodeResult")
    @RequestWrapper(localName = "GetAccessCodeResult", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.GetAccessCodeResult")
    @ResponseWrapper(localName = "GetAccessCodeResultResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.GetAccessCodeResultResponse")
    @WebResult(name = "GetAccessCodeResultResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.GetAccessCodeResultResponse2 getAccessCodeResult(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.GetAccessCodeResultRequest request
    );

    /**
     * This method allows merchants to refund an existing transaction.
     */
    @WebMethod(operationName = "DirectRefund", action = "https://api.ewaypayments.com/DirectRefund")
    @RequestWrapper(localName = "DirectRefund", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectRefund")
    @ResponseWrapper(localName = "DirectRefundResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.DirectRefundResponse")
    @WebResult(name = "DirectRefundResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.DirectRefundResponse2 directRefund(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.DirectRefundRequest request
    );

    /**
     * Captures payment against a previously authorised transaction.
     */
    @WebMethod(operationName = "CapturePayment", action = "https://api.ewaypayments.com/CapturePayment")
    @RequestWrapper(localName = "CapturePayment", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CapturePayment")
    @ResponseWrapper(localName = "CapturePaymentResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.CapturePaymentResponse")
    @WebResult(name = "CapturePaymentResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.CapturePaymentResponse2 capturePayment(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.CapturePaymentRequest request
    );

    /**
     * Returns a list of transactions that match the filter in the request.
     */
    @WebMethod(operationName = "TransactionSearch", action = "https://api.ewaypayments.com/TransactionSearch")
    @RequestWrapper(localName = "TransactionSearch", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.TransactionSearch")
    @ResponseWrapper(localName = "TransactionSearchResponse", targetNamespace = "https://api.ewaypayments.com/", className = "https.api_ewaypayments.TransactionSearchResponse")
    @WebResult(name = "TransactionSearchResult", targetNamespace = "https://api.ewaypayments.com/")
    public https.api_ewaypayments.TransactionSearchResponse2 transactionSearch(

        @WebParam(name = "request", targetNamespace = "https://api.ewaypayments.com/")
        https.api_ewaypayments.TransactionSearchRequest request
    );
}
