
drop table customer if exists;
create table customer (
	id integer generated by default as identity,
	name varchar(32) not null,
	pwd varchar(255) not null,
	fname varchar(32) not null,
	lname varchar(32) not null,
	birth varchar(255) not null,
	weight varchar(255) not null,
	email varchar(255),
	primary key (id)
);

drop table security_question_answer if exists;
create table security_question_answer (
	id integer generated by default as identity,
	customer integer not null,
	question varchar(255) not null,
	answer varchar(255) not null,
	primary key (id),
	foreign key(customer) references customer(id)
);

drop table authorities if exists;
drop table users if exists;

create table users (
  username varchar(255) not null primary key,
  password varchar(255) not null,
  enabled boolean not null
);

create table authorities (
  username varchar(255) not null,
  authority varchar(255) not null,
  constraint fk_authorities_users foreign key(username) references users(username)
);
