/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.active.vault;

import com.active.vault.util.FakerService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@ComponentScan
@EnableAutoConfiguration
@EntityScan(basePackages = {"com.active.vault.entity", "com.active.vault.util"})
@EnableJpaRepositories("com.active.vault.repository")
@SpringBootApplication
@ConfigurationProperties
public class App {

    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

    @Value("${app.init.faker.size}")
    private int size;

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    @Bean
    ApplicationRunner applicationRunner(FakerService fakerService) {
        return args -> fakerService.generate(size);
    }

}
