# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

spring:
  application:
    name: java-vault-demo
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
  cloud:
    vault:
      host: 127.0.0.1
      port: 8200
      scheme: http
      authentication: TOKEN
      token: s.3OfQ0FlooukDuL46DkL6J7qa

server:
  port: 8080
# ===================================================================
# Application specific properties
# ===================================================================
logging:
  file: vault.log
vault:
  transit:
    key:
      customer: customer
app:
  page:
    size: 20
  init:
    faker:
      size: 137

