# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

spring:
  application:
    name: java-vault-demo
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8086
# ===================================================================
# Application specific properties
# ===================================================================
logging:
  file: vault.log
vault:
  transit:
    key:
      customer: customer
app:
  page:
    size: 20
  init:
    faker:
      size: 137

